// <auto-generated />
using System;
using DBLayerPOC.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DBLayerPOC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200118220226_PaymentCurrencyCustomerVEndor")]
    partial class PaymentCurrencyCustomerVEndor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("TransportDbNew")
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DBLayerPOC.Infrastructure.Driver.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnName("Address")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("DriversLicenceExpDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DriversLicenceExpDate")
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 1, 18, 23, 2, 25, 923, DateTimeKind.Local).AddTicks(1603));

                    b.Property<string>("DriversLicenceNumber")
                        .IsRequired()
                        .HasColumnName("DriversLicenceNumber")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("IsInactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IsInactive")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastChangeDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LastChangeDateTime")
                        .HasColumnType("datetime2")
                        .HasDefaultValue(null);

                    b.Property<int?>("LastChangeUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LastChangeUserId")
                        .HasColumnType("int")
                        .HasDefaultValue(null);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("PassExpDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PassExpDate")
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 1, 18, 23, 2, 25, 923, DateTimeKind.Local).AddTicks(3118));

                    b.Property<string>("PassNumber")
                        .IsRequired()
                        .HasColumnName("PassNumber")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("PersonalIdExpDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PersonalIdExpDate")
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 1, 18, 23, 2, 25, 923, DateTimeKind.Local).AddTicks(2588));

                    b.Property<string>("PersonalIdNummber")
                        .IsRequired()
                        .HasColumnName("PersonalIdNummber")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnName("Remark")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("Driver");
                });

            modelBuilder.Entity("DBLayerPOC.Infrastructure.Login.LoginModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IsAdmin")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsInactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IsInactive")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastChangeDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LastChangeDateTime")
                        .HasColumnType("datetime2")
                        .HasDefaultValue(null);

                    b.Property<int?>("LastChangeUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LastChangeUserId")
                        .HasColumnType("int")
                        .HasDefaultValue(null);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .HasColumnName("Password")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Username")
                        .HasColumnName("Username")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("DBLayerPOC.Infrastructure.PurchaseInvoice.PurchaseInvoiceHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CreditMemo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CreditMemo")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DueDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DueDate")
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 1, 18, 23, 2, 25, 893, DateTimeKind.Local).AddTicks(635));

                    b.Property<string>("ExternalReferenceNo")
                        .HasColumnName("ExternalReferenceNo")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasColumnName("InvoiceNo")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("Invoiced")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Invoiced")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastChangeDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LastChangeDateTime")
                        .HasColumnType("datetime2")
                        .HasDefaultValue(null);

                    b.Property<int?>("LastChangeUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LastChangeUserId")
                        .HasColumnType("int")
                        .HasDefaultValue(null);

                    b.Property<bool>("Paid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Paid")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("PartiallyPayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PartiallyPayed")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PaymentDate")
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 1, 18, 23, 2, 25, 893, DateTimeKind.Local).AddTicks(5349));

                    b.Property<DateTime>("PostingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PostingDate")
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 1, 18, 23, 2, 25, 892, DateTimeKind.Local).AddTicks(9812));

                    b.Property<string>("PurchaseSupplierNumber")
                        .HasColumnName("PurchaseSupplierNumber")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("SupplierInvoiceNo")
                        .IsRequired()
                        .HasColumnName("SupplierInvoiceNo")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<float>("TotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TotalAmount")
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<float>("TotalAmountLocal")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TotalAmountLocal")
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("VendorId");

                    b.ToTable("PurchaseInvoiceHeader");
                });

            modelBuilder.Entity("DBLayerPOC.Infrastructure.PurchaseInvoice.PurchaseInvoiceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("Description")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<float>("DiscountPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DiscountPercent")
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<DateTime?>("LastChangeDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LastChangeDateTime")
                        .HasColumnType("datetime2")
                        .HasDefaultValue(null);

                    b.Property<int?>("LastChangeUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LastChangeUserId")
                        .HasColumnType("int")
                        .HasDefaultValue(null);

                    b.Property<float>("LineAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LineAmount")
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<int>("PurchaseHeaderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Quantity")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Remark")
                        .HasColumnName("Remark")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("TravelOrder")
                        .HasColumnName("TravelOrder")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<float>("UnitPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UnitPrice")
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<float>("VatPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("VatPercent")
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<int?>("VehicleId")
                        .HasColumnName("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseHeaderId");

                    b.ToTable("PurchaseInvoiceLine");
                });

            modelBuilder.Entity("DBLayerPOC.Infrastructure.SalesInvoice.SalesInvoiceHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AdrNeeded")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("AdrNeeded")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<float>("BruttoWeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("BruttoWeight")
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<float>("CalculatonExchangeRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CalculatonExchangeRate")
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<DateTime>("CheckIssueDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CheckIssueDate")
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 1, 18, 23, 2, 25, 911, DateTimeKind.Local).AddTicks(7227));

                    b.Property<DateTime>("ClienReceiptDocDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ClienReceiptDocDate")
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 1, 18, 23, 2, 25, 911, DateTimeKind.Local).AddTicks(7590));

                    b.Property<string>("CommodityType")
                        .HasColumnName("CommodityType")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<bool>("CreditMemo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CreditMemo")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("CrmNumber")
                        .HasColumnName("CrmNumber")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("DriverName")
                        .HasColumnName("DriverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DueDate")
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 1, 18, 23, 2, 25, 909, DateTimeKind.Local).AddTicks(6071));

                    b.Property<string>("ExternalReferenceNo")
                        .HasColumnName("ExternalReferenceNo")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasColumnName("InvoiceNo")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("Invoiced")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Invoiced")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastChangeDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LastChangeDateTime")
                        .HasColumnType("datetime2")
                        .HasDefaultValue(null);

                    b.Property<int?>("LastChangeUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LastChangeUserId")
                        .HasColumnType("int")
                        .HasDefaultValue(null);

                    b.Property<string>("LoadAddress")
                        .HasColumnName("LoadAddress")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("LoadDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LoadDate")
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 1, 18, 23, 2, 25, 911, DateTimeKind.Local).AddTicks(3808));

                    b.Property<string>("LoadRepresentative")
                        .HasColumnName("LoadRepresentative")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<double>("NumberOfPallets")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("NumberOfPallets")
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<double>("NumberOfPalletsPlaces")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("NumberOfPalletsPlaces")
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("OrderDate")
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 1, 18, 23, 2, 25, 909, DateTimeKind.Local).AddTicks(6505));

                    b.Property<bool>("OwnTransport")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("OwnTransport")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("Paid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Paid")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<float>("PartiallyPayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PartiallyPayed")
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PaymentDate")
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 1, 18, 23, 2, 25, 910, DateTimeKind.Local).AddTicks(1747));

                    b.Property<DateTime>("PostingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PostingDate")
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 1, 18, 23, 2, 25, 909, DateTimeKind.Local).AddTicks(5372));

                    b.Property<float>("PricePerKm")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PricePerKm")
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<string>("Remarks")
                        .HasColumnName("Remarks")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<float>("RouteDistance")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RouteDistance")
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<string>("SalesPerson")
                        .HasColumnName("SalesPerson")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("TaxLawText")
                        .HasColumnName("TaxLawText")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(5000);

                    b.Property<float>("TotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TotalAmount")
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<float>("TotalAmountLocal")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TotalAmountLocal")
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<string>("TravelOrder")
                        .HasColumnName("TravelOrder")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("UnloadAddress")
                        .HasColumnName("UnloadAddress")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("UnloadDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UnloadDate")
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 1, 18, 23, 2, 25, 911, DateTimeKind.Local).AddTicks(5304));

                    b.Property<string>("VechicleRegistration")
                        .HasColumnName("VechicleRegistration")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("CustomerId");

                    b.ToTable("SalesInvoiceHeader");
                });

            modelBuilder.Entity("DBLayerPOC.Infrastructure.SalesInvoice.SalesInvoiceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("Description")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<float>("DiscountPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DiscountPercent")
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<DateTime?>("LastChangeDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LastChangeDateTime")
                        .HasColumnType("datetime2")
                        .HasDefaultValue(null);

                    b.Property<int?>("LastChangeUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LastChangeUserId")
                        .HasColumnType("int")
                        .HasDefaultValue(null);

                    b.Property<float>("LineAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LineAmount")
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Quantity")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Remark")
                        .HasColumnName("Remark")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int>("SalesHeaderId")
                        .HasColumnType("int");

                    b.Property<float>("UnitPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UnitPrice")
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<float>("VatPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("VatPercent")
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.HasKey("Id");

                    b.HasIndex("SalesHeaderId");

                    b.ToTable("SalesInvoiceLine");
                });

            modelBuilder.Entity("DBLayerPOC.Infrastructure.Settings.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("LastChangeDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LastChangeDateTime")
                        .HasColumnType("datetime2")
                        .HasDefaultValue(null);

                    b.Property<int?>("LastChangeUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LastChangeUserId")
                        .HasColumnType("int")
                        .HasDefaultValue(null);

                    b.Property<int>("LastUsedNumber")
                        .HasColumnName("LastUsedNumber")
                        .HasColumnType("int");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasColumnName("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnName("Prefix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnName("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("DBLayerPOC.Infrastructure.Vehicle.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChassisNumber")
                        .IsRequired()
                        .HasColumnName("ChassisNumber")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("IsInactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IsInactive")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastChangeDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LastChangeDateTime")
                        .HasColumnType("datetime2")
                        .HasDefaultValue(null);

                    b.Property<int?>("LastChangeUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LastChangeUserId")
                        .HasColumnType("int")
                        .HasDefaultValue(null);

                    b.Property<float>("MaxWeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MaxWeight")
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnName("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnName("RegistrationNumber")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnName("Remark")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("VechicleType")
                        .IsRequired()
                        .HasColumnName("VechicleType")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("DBLayerPOC.Infrastructure.Vendor.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnName("Address")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnName("City")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnName("Country")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("Email")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool?>("IsInactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IsInactive")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastChangeDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LastChangeDate")
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 1, 18, 23, 2, 25, 883, DateTimeKind.Local).AddTicks(7096));

                    b.Property<DateTime?>("LastChangeDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastChangeUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("PaymentCurrency")
                        .HasColumnName("PaymentCurrency")
                        .HasColumnType("int");

                    b.Property<string>("PaymentTermsCode")
                        .IsRequired()
                        .HasColumnName("PaymentTermsCode")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnName("PhoneNo")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("VatNumber")
                        .HasColumnName("VatNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vendor");
                });

            modelBuilder.Entity("DBLayerPOC.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("Code")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<DateTime?>("LastChangeDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LastChangeDateTime")
                        .HasColumnType("datetime2")
                        .HasDefaultValue(null);

                    b.Property<int?>("LastChangeUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LastChangeUserId")
                        .HasColumnType("int")
                        .HasDefaultValue(null);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Currency");
                });

            modelBuilder.Entity("DBLayerPOC.Models.CurrencyExchangeRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrencyId")
                        .HasColumnName("CurrencyId")
                        .HasColumnType("int");

                    b.Property<float>("ExchangeRateAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ExchangeRateAmount")
                        .HasColumnType("real")
                        .HasDefaultValue(1f);

                    b.Property<DateTime?>("LastChangeDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LastChangeDateTime")
                        .HasColumnType("datetime2")
                        .HasDefaultValue(null);

                    b.Property<int?>("LastChangeUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LastChangeUserId")
                        .HasColumnType("int")
                        .HasDefaultValue(null);

                    b.Property<DateTime>("StartingDate")
                        .HasColumnName("StartingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("CurrencyExchangeRate");
                });

            modelBuilder.Entity("DBLayerPOC.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnName("Address")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnName("City")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnName("Country")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("Email")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("IsInactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IsInactive")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastChangeDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LastChangeDateTime")
                        .HasColumnType("datetime2")
                        .HasDefaultValue(null);

                    b.Property<int?>("LastChangeUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LastChangeUserId")
                        .HasColumnType("int")
                        .HasDefaultValue(null);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("PaymentCurrency")
                        .HasColumnName("PaymentCurrency")
                        .HasColumnType("int");

                    b.Property<string>("PersonalIdNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PersonalIdNumber")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50)
                        .HasDefaultValue(null);

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnName("PhoneNo")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("VatNumber")
                        .HasColumnName("VatNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("DBLayerPOC.Infrastructure.PurchaseInvoice.PurchaseInvoiceHeader", b =>
                {
                    b.HasOne("DBLayerPOC.Models.Currency", "Currency")
                        .WithMany("PurchaseInvoiceHeaders")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBLayerPOC.Infrastructure.Vendor.Vendor", "Vendor")
                        .WithMany("PurchaseInvoiceHeaders")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DBLayerPOC.Infrastructure.PurchaseInvoice.PurchaseInvoiceLine", b =>
                {
                    b.HasOne("DBLayerPOC.Infrastructure.PurchaseInvoice.PurchaseInvoiceHeader", "Header")
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DBLayerPOC.Infrastructure.SalesInvoice.SalesInvoiceHeader", b =>
                {
                    b.HasOne("DBLayerPOC.Models.Currency", "Currency")
                        .WithMany("SalesInvoiceHeaders")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBLayerPOC.Models.Customer", "Customer")
                        .WithMany("SalesInvoiceHeaders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DBLayerPOC.Infrastructure.SalesInvoice.SalesInvoiceLine", b =>
                {
                    b.HasOne("DBLayerPOC.Infrastructure.SalesInvoice.SalesInvoiceHeader", "Header")
                        .WithMany("Lines")
                        .HasForeignKey("SalesHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DBLayerPOC.Models.CurrencyExchangeRate", b =>
                {
                    b.HasOne("DBLayerPOC.Models.Currency", "Currency")
                        .WithMany("CurrencyExchangeRates")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
